name: CD Pipeline
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Логин в DockerHub
      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Шаг 3: Сборка Docker-образа
      - name: Build Docker image
        run: docker build -t yourusername/simple-app:latest .

      # Шаг 4: Загрузка Docker-образа в DockerHub
      - name: Push Docker image
        run: docker push yourusername/simple-app:latest

      # Шаг 5: Развертывание на AWS ECS
      - name: Deploy to AWS ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          cluster: your-cluster-name                  # Имя ECS-кластера
          service: your-service-name                 # Имя ECS-сервиса
          task-definition: your-task-definition.json # JSON-файл с описанием задачи
          wait-for-service-stability: true           # Ожидание стабильного состояния
