name: CD Pipeline
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Логин в Vercel
      - name: Vercel login
        run: |
          echo ${{ secrets.VERCEL_TOKEN }} | vercel login --token

      # Шаг 3: Развертывание на Vercel
      - name: Deploy to Vercel
        run: |
          vercel --prod --confirm
