name: CI for Flask App

# Trigger the workflow on push events to the main branch
on:
  push:
    branches:
      - main  # This triggers the workflow whenever code is pushed to the "main" branch

jobs:
  build:
    runs-on: ubuntu-latest  # The job will run on the latest version of Ubuntu

    steps:
    # Step 1: Check out the repository to the GitHub Actions runner
    - name: Check out repository
      uses: actions/checkout@v2  # Action to clone the repository onto the runner

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2  # Action to install the specified Python version
      with:
        python-version: 3.13  # Specify the version of Python to use

    # Step 3: Install dependencies required for the application
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Update pip to the latest version
        pip install -r requirements.txt  # Install dependencies from the requirements file

    # Step 4: Log in to Vercel for deployment
    - name: Log in to Vercel
      run: |
        curl -sL https://github.com/vercel/vercel/releases/download/v25.1.0/vercel-linux-x64.tar.gz | tar xz
        sudo mv vercel /usr/local/bin/  # Install Vercel CLI on the runner
        vercel login ${{ secrets.VERCEL_TOKEN }}  # Log in to Vercel using a secure token stored in GitHub Secrets

    # Step 5: Deploy the application to Vercel
    - name: Deploy to Vercel
      run: |
        vercel --prod --token ${{ secrets.VERCEL_TOKEN }}  # Deploy the application to the production environment in Vercel
