name: CI for Flask App

on:
  push:
    branches:
      - main  # Это будет запускать процесс при пуше в ветку main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.13

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Log in to Vercel
      run: |
        curl -sL https://github.com/vercel/vercel/releases/download/v25.1.0/vercel-linux-x64.tar.gz | tar xz
        sudo mv vercel /usr/local/bin/
        vercel login ${{ secrets.VERCEL_TOKEN }}

    - name: Deploy to Vercel
      run: |
        vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
